Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -1,9 +1,9 @@
 name: Build Kernel
 on:
-  #watch:
-    #types: [started]
-  #schedule:
-   # - cron: "0 0 * * 0"
+  watch:
+    types: [started]
+  schedule:
+    - cron: "0 0 * * 0"
   workflow_dispatch:
 
 jobs:
@@ -756,6 +756,42 @@ jobs:
         path: |
           kernel_workspace/android-kernel/out/drivers/kernelsu/kernelsu.ko
 
+  telegram-bot-api:
+    name: Telegram Bot API
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Clone Telegram Bot API
+        run: |
+          git clone --recursive https://github.com/tdlib/telegram-bot-api.git
+          git status telegram-bot-api >> telegram-bot-api-status
+      - name: Cache Bot API Binary
+        id: cache-bot-api
+        uses: actions/cache@v4
+        with:
+          path: telegram-bot-api-binary
+          key: CI-telegram-bot-api-${{ hashFiles('telegram-bot-api-status') }}
+      - name: Compile Telegram Bot API
+        if: steps.cache-bot-api.outputs.cache-hit != 'true'
+        run: |
+          sudo apt-get update
+          sudo apt-get install make git zlib1g-dev libssl-dev gperf cmake g++
+          cd telegram-bot-api
+          rm -rf build
+          mkdir build
+          cd build
+          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
+          cmake --build . --target install -j$(nproc)
+          cd ../..
+          ls -l telegram-bot-api/bin/telegram-bot-api*
+          cp telegram-bot-api/bin/telegram-bot-api telegram-bot-api-binary
+      - name: Upload Binary
+        uses: actions/upload-artifact@master
+        with:
+          name: telegram-bot-api-binary
+          path: telegram-bot-api-binary
+
   check-member:
     runs-on: ubuntu-latest
     outputs:
@@ -780,6 +816,137 @@ jobs:
             echo "is_member=false"
           fi
 
+  upload-to-telegram:
+    name: Upload Telegram
+    if: |
+      success() &&
+      (
+      (github.event_name != 'watch' && 1 && 1) ||
+      (github.event_name == 'watch' && needs.check-member.outputs.is_member == 'true')
+      )
+    runs-on: ubuntu-22.04
+    needs:
+      - build
+      - telegram-bot-api
+      - check-member
+    steps:
+      - name: Download Artifacts
+        uses: actions/download-artifact@v4
+        with:
+          path: artifacts
+
+      - name: Display structure of downloaded files
+        run: ls -R artifacts
+
+      - name: Download Telegram Bot API Binary
+        uses: actions/download-artifact@master
+        with:
+          name: telegram-bot-api-binary
+          path: .
+
       - name: Zip AnyKernel3
         run: |
           (cd artifacts/AnyKernel3*/ && zip -r AnyKernel3.zip * && mv AnyKernel3.zip ..)
+
+      - name: Release to Telegram
+        env:
+          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
+          COMMIT_URL: ${{ github.event.head_commit.url }}
+        continue-on-error: true
+        run: |
+          # TODO: https://github.com/LSPosed/LSPatch/blob/master/.github/workflows/main.yml
+          export ACTION_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+          export GITHUB_WORKFLOW
+
+          chmod +x telegram-bot-api-binary
+          nohup ./telegram-bot-api-binary \
+            --api-id=${{ secrets.TG_API_ID }} \
+            --api-hash=${{ secrets.TG_API_HASH }} \
+            --local \
+            --http-port=8081 \
+            --log=telegram.log &
+
+          timeout 10s bash -c 'until curl -s http://127.0.0.1:8081 >/dev/null; do sleep 1; done'
+
+          upload_file() {
+            local pattern=$1
+            local file=$(find artifacts -type f -name "$pattern" | head -1)
+            if [[ -f "$file" ]]; then
+              echo "📤 Uploading $category: $file"
+              curl --progress-bar \
+                "http://127.0.0.1:8081/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument" \
+                -F "chat_id=${{ secrets.CHAT_ID }}" \
+                -F "document=@$file" || echo "❌ Upload failed: $file"
+            else
+              echo "⚠️ Not found: $pattern"
+              return 1
+            fi
+          }
+
+          upload_file_with_caption() {
+            local pattern=$1
+            local category=$2
+            local file=$(find artifacts -type f -name "$pattern" | head -1)
+            
+            if [[ -f "$file" ]]; then
+              local caption="[${GITHUB_WORKFLOW}] ${category} Build Success
+          🔗 Action: ${ACTION_URL}
+          💬 Commit: ${COMMIT_MESSAGE//$'\n'/ }"
+              
+              echo "📤 Uploading $category: $file"
+              curl --progress-bar \
+                "http://127.0.0.1:8081/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument" \
+                -F "chat_id=${{ secrets.CHAT_ID }}" \
+                -F "document=@$file" \
+                -F "caption=${caption:0:1024}" || echo "❌ Upload failed: $file"
+            else
+              echo "⚠️ Not found: $pattern"
+              return 1
+            fi
+          }
+
+          upload_file_with_caption "AnyKernel3.zip" "KernelPackage" && \
+          # upload_file "Image" "KernelImage" && \
+          # upload_file "boot.img" "BootImage" && \
+          # upload_file "*defconfig" "KernelConfig"
+
+          if ps aux | grep -q '[t]elegram-bot-api'; then
+            pkill -f telegram-bot-api-binary
+            echo "✅ Bot API stopped"
+          else
+            echo "⚠️ Bot API process not found"
+          fi
+
+  notify:
+    runs-on: ubuntu-latest
+    if: |
+      (
+      (github.event_name != 'watch' && 1 && 1) ||
+      (github.event_name == 'watch' && needs.check-member.outputs.is_member == 'true')
+      )
+    needs:
+      - build
+      - check-member
+    steps:
+      - name: Send NTFY notifications
+        env:
+          NTFY_SUBSCRIPTIONS: ${{ secrets.NTFY_SUBSCRIPTIONS }}
+        continue-on-error: true
+        run: |
+          IFS=' ' read -r -a subscriptions <<< "$NTFY_SUBSCRIPTIONS"
+
+          ACTION_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+
+          BUILD_RESULT=${{ needs.build.result }}
+
+          for url in "${subscriptions[@]}"; do
+            curl -X POST \
+              -H "Title: GitHub Action Notification" \
+              -H "Priority: high" \
+              -H "Actions: view, Open Action, $ACTION_URL" \
+              -d "Workflow: $GITHUB_WORKFLOW
+          Branch: $GITHUB_REF_NAME
+          Build result: $BUILD_RESULT
+          Action run link: $ACTION_URL" \
+              "$url"
+          done
